<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class ButtonZaloOptions
{
    private $button_zalo_options;

    public function __construct()
    {
        add_action('admin_menu', array($this, 'button_zalo_add_plugin_page'));
        add_action('admin_init', array($this, 'button_zalo_page_init'));
    }

    public function button_zalo_add_plugin_page()
    {
        add_options_page(
            'Button Zalo', // page_title
            'Button Zalo', // menu_title
            'manage_options', // capability
            'button-zalo', // menu_slug
            array($this, 'button_zalo_create_admin_page') // function
        );
    }

    public function button_zalo_create_admin_page()
    {
        $this->button_zalo_options = get_option('button_zalo_option_name'); ?>

        <div class="wrap">
            <h2>Button Zalo</h2>
            <p></p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields('button_zalo_option_group');
                do_settings_sections('button-zalo-admin');
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function button_zalo_page_init()
    {
        register_setting(
            'button_zalo_option_group', // option_group
            'button_zalo_option_name', // option_name
            array($this, 'button_zalo_sanitize') // sanitize_callback
        );

        add_settings_section(
            'button_zalo_setting_section', // id
            'Thiết lập button Zalo', // title
            array($this, 'button_zalo_section_info'), // callback
            'button-zalo-admin' // page
        );

        add_settings_field(
            'so_dien_thoai_0', // id
            'Số điện thoại', // title
            array($this, 'so_dien_thoai_0_callback'), // callback
            'button-zalo-admin', // page
            'button_zalo_setting_section' // section
        );

        add_settings_field(
            'qr_id_1', // id
            'QR ID', // title
            array($this, 'qr_id_1_callback'), // callback
            'button-zalo-admin', // page
            'button_zalo_setting_section', // section
        );

        add_settings_field(
            'vi_tri_2', // id
            'Vị trí', // title
            array($this, 'vi_tri_2_callback'), // callback
            'button-zalo-admin', // page
            'button_zalo_setting_section' // section
        );
    }

    public function button_zalo_sanitize($input)
    {
        $sanitary_values = array();
        if (isset($input['so_dien_thoai_0'])) {
            $sanitary_values['so_dien_thoai_0'] = sanitize_text_field($input['so_dien_thoai_0']);
        }

        if (isset($input['qr_id_1'])) {
            $sanitary_values['qr_id_1'] = sanitize_text_field($input['qr_id_1']);
        }

        if (isset($input['vi_tri_2'])) {
            $sanitary_values['vi_tri_2'] = $input['vi_tri_2'];
        }

        return $sanitary_values;
    }

    public function button_zalo_section_info()
    {
    }

    public function so_dien_thoai_0_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="button_zalo_option_name[so_dien_thoai_0]" id="so_dien_thoai_0" value="%s">',
            isset($this->button_zalo_options['so_dien_thoai_0']) ? esc_attr($this->button_zalo_options['so_dien_thoai_0']) : ''
        );
    
    }

    public function qr_id_1_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="button_zalo_option_name[qr_id_1]" id="qr_id_1" value="%s">',
            isset($this->button_zalo_options['qr_id_1']) ? esc_attr($this->button_zalo_options['qr_id_1']) : ''
        );
        printf('<p class="description"> %s</p>', __('Lấy QR ID bằng cách upload ảnh lên website qrcoderaptor.com', 'zalo-button-fix'));
    }

    public function vi_tri_2_callback()
    {
        if(!isset($this->button_zalo_options['vi_tri_2']))
            $this->button_zalo_options['vi_tri_2'] = 'left';
    ?> <fieldset><?php $checked = (isset($this->button_zalo_options['vi_tri_2']) && $this->button_zalo_options['vi_tri_2'] === 'left') ? 'checked' : ''; ?>
            <label for="vi_tri_2-0"><input type="radio" name="button_zalo_option_name[vi_tri_2]" id="vi_tri_2-0" value="left" <?php echo $checked; ?>> Trái</label><br>
            <?php $checked = (isset($this->button_zalo_options['vi_tri_2']) && $this->button_zalo_options['vi_tri_2'] === 'right') ? 'checked' : ''; ?>
            <label for="vi_tri_2-1"><input type="radio" name="button_zalo_option_name[vi_tri_2]" id="vi_tri_2-1" value="right" <?php echo $checked; ?>> Phải</label>
        </fieldset> <?php
                }
            }
            if (is_admin())
                $button_zalo = new ButtonZaloOptions();

/* 
 * Retrieve this value with:
 * $button_zalo_options = get_option( 'button_zalo_option_name' ); // Array of All Options
 * $so_dien_thoai_0 = $button_zalo_options['so_dien_thoai_0']; // Số điện thoại
 * $qr_id_1 = $button_zalo_options['qr_id_1']; // QR ID
 * $vi_tri_2 = $button_zalo_options['vi_tri_2']; // Vị trí
 */
